SI-2707-vehicle-by-sd
DIMO-Network/identity-api pull request #109
Opened 2024-06-11 18:45 UTC by Allyson-English

find vehicle a synthetic device is connected to

2024-06-13 13:02 UTC, KevinJoiner approved these changes

2024-06-13 20:25 UTC, elffjs commented on graph/schema/synthetic.graphqls
> +  vehicle: Vehicle
Probably `Vehicle!` for now?

2024-06-13 20:38 UTC, elffjs commented on internal/repositories/synthetic/synthetic_devices.go
> +	} else if before != nil {
Both can be specified. That's legal.

2024-06-13 20:38 UTC, elffjs commented on internal/repositories/synthetic/synthetic_devices.go
> +	orderBy := " DESC"
Is this a good change?

2024-06-17 18:15 UTC, elffjs commented
@Allyson-English Giving this a nudge.

2024-06-17 20:55 UTC, Allyson-English commented
@elffjs thanks for nudging! I made those edits on friday but forgot to push them up because I got distracted by cases of if/ else for the before/ after queries. I removed the use of it here because you pointed out that it's legal but noticed that we're also doing it in these spots and was wondering if we wanted to use this opportunity to make both options allowable in those instances too: [1](https://github.com/DIMO-Network/identity-api/blob/main/internal/repositories/aftermarket/aftermarket_devices.go#L82), [2](https://github.com/DIMO-Network/identity-api/blob/main/internal/repositories/dcn/dcn.go#L127), [3](https://github.com/DIMO-Network/identity-api/blob/main/internal/repositories/reward/rewards.go#L83)

2024-06-17 20:58 UTC, elffjs commented
That's a good catch. I can do that in another PR, no worries.

I don't think it's a very _useful_ option but unlike combining first and last it doesn't seem to do any harm.

2024-06-17 20:59 UTC, elffjs requested changes

2024-06-17 20:59 UTC, elffjs commented on internal/repositories/synthetic/synthetic_devices.go
> +		VehicleID:     &sd.VehicleID,
We need to regenerate, I think? This isn't a pointer anymore.

2024-06-17 21:06 UTC, elffjs commented on graph/schema/synthetic.graphqls
> +  The vehicle, if any, with which the synthetic device is paired.
I think we can remove the `if any` here.

2024-06-17 21:07 UTC, elffjs commented on internal/repositories/synthetic/synthetic_devices.go
> +	orderBy := " DESC"
(I do not think it is)

2024-06-17 21:32 UTC, merged