Update URL creation to be more robust.
DIMO-Network/identity-api pull request #87
Opened 2024-03-25 15:40 UTC by KevinJoiner

2024-03-26 18:14 UTC, 0xdev22 requested changes

2024-03-26 18:14 UTC, 0xdev22 commented on internal/repositories/aftermarket/aftermarket_devices.go
> +func GetAftermarketDeviceImageUrl(baseURL string, tokenID int) (string, error) {
Can you add a test for this too the way we have a test for `GetVehicleImageUrl`

2024-04-17 14:55 UTC, Allyson-English approved these changes

2024-04-28 20:19 UTC, elffjs requested changes
Minor things.

2024-04-28 20:19 UTC, elffjs commented on internal/loader/aftermarket_device_loader.go
> +			imageUrl, err := aftermarket.GetAftermarketDeviceImageUrl(ad.settings.BaseImageURL, am.ID)
```suggestion
			imageURL, err := aftermarket.GetAftermarketDeviceImageUrl(ad.settings.BaseImageURL, am.ID)
```

Similarly in other places.

It's weird that this call can fail. I guess the culprit is [`url.Parse`](https://cs.opensource.google/go/go/+/refs/tags/go1.22.2:src/net/url/url.go;l=1266).

2024-04-28 20:19 UTC, elffjs commented on internal/repositories/aftermarket/aftermarket_devices.go
> +		return nil, fmt.Errorf("faile to get image url: %w", err)
```suggestion
		return nil, fmt.Errorf("failed to get image url: %w", err)
```

2024-04-29 18:31 UTC, elffjs commented on internal/loader/aftermarket_device_loader.go
> +			imageUrl, err := aftermarket.GetAftermarketDeviceImageUrl(ad.settings.BaseImageURL, am.ID)
Is it resolved? I think Go casing is `imageURL`.

2024-04-30 21:25 UTC, elffjs commented on internal/loader/aftermarket_device_loader.go
> +			imageUrl, err := aftermarket.GetAftermarketDeviceImageUrl(ad.settings.BaseImageURL, am.ID)
I made a PR into your PR #94

2024-05-01 21:35 UTC, elffjs approved these changes

2024-05-03 19:03 UTC, elffjs commented
Good to merge, I think?

2024-05-06 22:01 UTC, merged